### ISSUE TITLE
Installs in directory "onetimesecret-0.10.1" but wants to compile "onetimesecret-v0.10.1"

### ISSUE THREAD

**Issue by AnonSS** [markt-de/puppet-onetimesecret#4]
I am using Rocky Linux 8, puppet onetimesecret 2.2.0.

**Comment by AnonSS** [comment]
The same is true for v0.11.0.

**Comment by AnonSS** [comment]
Hello, to update, I can get around this error by using the commit ID instead of version.  However I now get this new error:

Error: /Stage[main]/Onetimesecret::Install/Exec[build onetimesecret version e858f1edde6cc6af7ef75aa45f2bb9f9b0f0ecf5 from source package]: Failed to call refresh: '/usr/bin/bundle install --deployment --frozen --without=dev' returned 1 instead of one of [0]
Error: /Stage[main]/Onetimesecret::Install/Exec[build onetimesecret version e858f1edde6cc6af7ef75aa45f2bb9f9b0f0ecf5 from source package]: '/usr/bin/bundle install --deployment --frozen --without=dev' returned 1 instead of one of [0]_

**Comment by Lightning-** [comment]
actually, we fixed this issue some time ago with cf618b2 but forgot to mention this here, sry for that.

as well with the current work on this module the bundle installations should work again; mostly this is an issue with the supported ruby versions of onetimesecret (we adjusted our module accordingly).  
so using the current main branch or the next upcoming release, you should be able to run rocky 8 (by switching to dnf module `ruby:3.1`) + ots 0.16.0 again.

EDIT: note for running on the main branch currently: we added a dependency of https://github.com/markt-de/puppet-marktlib for our future use (and this is not documented yet). so you likely want to add this to your puppetfile too :wink:.
